services:
  db:
    build:
      context: .
      dockerfile: database/dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports: 
      - 3306:${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      #- database/db.sql:/docker-entrypoint-initdb.database/db.sql
    networks:
      - local_network

  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    networks:
      - local_network
    command: 
      sh -c "python ./backend/manage.py runserver 8000"
    depends_on: #links:
      - db
  
  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    networks:
      - local_network
    depends_on:
      - backend

volumes:
  mysql_data:
    external: true

networks:
  local_network:
    name: local_network
