FROM python:latest
WORKDIR /app
COPY . .
#RUN python -m venv venv
#RUN python venv/bin/pip install -r requirements.txt

RUN pip install -r ./backend/requirements.txt
RUN apt install -y --no-install-recommends git
RUN git config --global user.name "JUAN CARLOS ANDRADE ESPERANZA"
RUN git config --global user.email "jandradee@outlook.com"


#RUN django-admin startproject admin ./backend
RUN mkdir ./backend/core
RUN cd ./backend/core
#RUN python ./backend/manage.py startapp core /core