# Generated by Django 5.1.5 on 2025-01-17 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('birth_day', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=100)),
                ('driver_license', models.CharField(blank=True, max_length=20)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.DateField()),
                ('Languaje', models.CharField(max_length=200)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=200)),
                ('company_or_organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('profile_head_line', models.CharField(max_length=255)),
                ('languaje', models.CharField(max_length=200)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.CharField(blank=True, max_length=200)),
                ('Image', models.ImageField(blank=True, upload_to='education/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lang', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, upload_to='courses/')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lang', models.CharField(max_length=200)),
                ('exp_date', models.CharField(max_length=200)),
                ('certification_number', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, upload_to='certifications/')),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
        ),
    ]
