# Generated by Django 5.1.5 on 2025-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='Image',
            field=models.ImageField(blank=True, upload_to='volunteering/'),
        ),
    ]
